.gitattributes, end-end-tests/api-standards/components/common.yaml, end-end-tests/api-standards/components/errors.yaml, end-end-tests/api-standards/components/headers/headers.yaml, end-end-tests/api-standards/components/parameters/pagination.yaml, end-end-tests/api-standards/components/parameters/version.yaml, end-end-tests/api-standards/components/responses/204.yaml, end-end-tests/api-standards/components/responses/400.yaml, end-end-tests/api-standards/components/responses/401.yaml, end-end-tests/api-standards/components/responses/403.yaml, end-end-tests/api-standards/components/responses/404.yaml, end-end-tests/api-standards/components/responses/409.yaml, end-end-tests/api-standards/components/responses/500.yaml, end-end-tests/api-standards/components/tag.yaml, end-end-tests/api-standards/components/types.yaml, end-end-tests/api-standards/components/version.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/000-baseline.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/001-fail-breaking-param-change.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/001-fail-operation-removed.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/001-fail-operationid-change.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/001-fail-stability-change.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/002-ok-add-operation.yaml
This adds some test data for evaluating differential rules, illustrating
changes that should pass and fail.
=> chore: add API standards scenario

end-end-tests/api-standards/resources/thing/2021-11-10/000-baseline.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/001-ok-add-property-field.yaml
Fix a few lint errors in e2e test specs.
=> chore: fix some baseline / should-be-ok spec changes

.circleci/config.yml, package.json, src/index.ts, src/rulesets/headers.ts, src/rulesets/properties.ts, src/rulesets/tests/fixtures.ts, src/rulesets/tests/inputs/operationIds.ts, src/rulesets/tests/operations.test.ts, yarn.lock
Adding scripts to run format and lint, check for formatting in CI.
=> chore: format and lint scripts, add lint to CI

Dockerfile, package.json, scripts/build-docker.bash, scripts/run-docker.bash
Fix problems in the previous Dockerfile optimization changes. ~~ON HOLD pending #99.~~
=> fix: optimized docker image

package.json, yarn.lock
Addresses: https://github.com/snyk/sweater-comb/issues/108
The `bulk-compare` command will now return an exit code `1` on:
- Any failure loading the file (or input files)
- Any failed check
Output
Passing run:
```
4 checks passed
0 checks failed
$ echo $?
0
```
failing run:
```
0 checks passed
4 checks failed
$ echo $?
1
```
=> fix: bulk-compare exit code on error

package.json, src/dsl.ts, src/rulesets/tests/__snapshots__/lifecycle.test.ts.snap, src/rulesets/tests/lifecycle.test.ts, yarn.lock
- https://github.com/snyk/sweater-comb/issues/114 -- Fixed this, accidental regression from bulk-compare -- sorry about this
=> Fix for compare command

package.json, src/changelog.ts, yarn.lock
Add a command that shows the changelog as a delta between two OpenAPI
specs.
=> feat: changelog command

.circleci/config.yml
Trying to debug docker image build.
=> chore: debug output for docker push

.circleci/config.yml, package.json, yarn.lock
sweater-comb is a yarn project, it needs to be semantic-released with
yarn.
=> fix: use semantic-release with yarn

src/docs.ts, src/rulesets/tests/__snapshots__/end-end.test.ts.snap
This is a rebase of #180 with commitlint fixed.
finish the updating links to correct ones in sweater comb
cleanup fmt
=> fix: Update JSON API docs

src/rulesets/operations.ts, src/rulesets/tests/__snapshots__/operations.test.ts.snap, src/rulesets/tests/operations.test.ts, yarn.lock
=> feat: allow /self having no tenant

src/workflows/templates/operations/create.ts, src/workflows/templates/operations/update.ts, src/workflows/templates/schemas.ts
From session w/ group 6
@cmars  -- take a look at these to make sure the generators are correct. We did not wrap create / update with `data`
=> Fixed content type for create / update types

end-end-tests/workflows/.vervet.yaml, package.json, src/workflows/file-resolvers.ts, src/workflows/tests/file-resolver.test.ts, src/workflows/tests/vervet-resolver.test.ts, src/workflows/vervet-resolver.ts, yarn.lock
Use vervet project configuration to locate where resources are defined
for workflow commands.
=> feat: automatically discover default vervet resources directory

end-end-tests/api-standards/resources/thing/2021-11-10/002-fail-singleton-no-pagination.yaml, end-end-tests/api-standards/test-bulk.bash, src/rulesets/jsonapi.ts
Singletons are not paginated, and pagination parameters should not be
allowed on singletons.
=> fix: singletons are not paginated

docs/standards/rest.md
=> chore: formatting fixes in rest standards docs

docs/principles/version.md
Fix rendering of markdown bullets
=> docs: fix versioning bullets

src/rulesets/rest/2022-05-25/json-api-rules/resource-object-rules.ts, src/workflows/templates/schemas.ts
Fixes: https://github.com/snyk/sweater-comb/issues/257
=> fix: adds missing type for response bodies

.circleci/config.yml, package.json, src/woollypully/__tests__/checker.test.ts, src/woollypully/__tests__/config.test.ts, src/woollypully/__tests__/static_readiness_ok/Tiltfile, src/woollypully/__tests__/static_readiness_ok/fake-service/k8s/cerberus-configmap.yaml, src/woollypully/__tests__/static_readiness_ok/fake-service/k8s/deployment.yaml, src/woollypully/config.ts, src/woollypully/index.ts, yarn.lock
=> chore: add woollypully sidecar build and publish

docs/principles/jsonapi.md, docs/standards/rest.md
Proposal on how Snyk APIs will support API expansion of related
resources in responses.
=> chore: documentation on expansion of related resources.

docs/standards/rest.md
Defining a `meta` object convention for representing collection counts,
and query parameters to request counts on collections.
=> chore: document collection counts metadata & parameters

src/rulesets/rest/2022-05-25/__tests__/property-rules.test.ts, src/rulesets/rest/2022-05-25/utils.ts
Support nested composite types when checking that an array type is fully
defined.
=> fix: recursively check for fully-defined array types

package.json, yarn.lock
Fix several known issues in parse-url and other deps.
=> chore: bump dependency versions

docs/standards/rest.md
Make it clearer when meta objects should and should/must not be used.
Prettier on save picked up some other changes. I can back those out if they're a problem.
=> chore: clarify when meta objects are appropriate

.circleci/config.yml
Fix CI step with `snyk container test`
=> fix: add snyk scan step in ci

.circleci/config.yml, yarn.lock
Adds Snyk scan deps and scan code jobs to the CI.
=> chore: add Snyk scan jobs

.circleci/config.yml
Snyk-on-Snyk program: moving from platform-access to platform-extensibility
-- 
*PR auto-generated. Please review carefully.*
=> chore(snyk): snyk-on-snyk targetting platform-extensibility org

package.json, yarn.lock
The bundled dependencies list was not updated to match the updated dependency list.
=> fix: correct bundled dependencies after update

docs/standards/rest.md
This decision came out of a (lightly attended) #guild-api chat on Sept 25, 2023.
=> Clarify null response handling

docs/standards/rest.md
Add docs for range numerical filters.
=> docs: add docs for numerical filters

end-end-tests/api-standards/context-ga.json, end-end-tests/api-standards/resources/thing/2021-11-10/004-baseline-beta-with-error-and-new-error.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/004-baseline-beta-with-error-and-no-new-error.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/004-baseline-beta-with-error.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/004-baseline-ga-with-error-and-new-error.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/004-baseline-ga-with-error-and-no-new-error.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/004-baseline-ga-with-error.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/004-baseline-with-error-and-new-error.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/004-baseline-with-error-and-no-new-error.yaml, end-end-tests/api-standards/resources/thing/2021-11-10/004-baseline-with-error.yaml, end-end-tests/api-standards/test.bash, package-lock.json, package.json, src/__tests__/lint.test.ts
Update useoptic dependencies to fix axios vulnerability
=> fix: update optic to 0.54.4

.circleci/config.yml, Dockerfile, package-lock.json, package.json, scripts/build-npm.bash
Revert to node18 and semantic-release 22
=> feat: revert to node18

.circleci/config.yml, .gitleaksignore
Add [secrets scanning](https://snyksec.atlassian.net/wiki/spaces/PRODSEC/pages/1563787412/Secrets+Scanning)
=> chore: add secrets scanning [PRDS-436]

components/common.yaml, docs/standards/rest.md, end-end-tests/api-standards/resources/thing/2021-11-10/003-jsonapi.yaml, src/rulesets/rest/2022-05-25/json-api-rules/status-code-rules.ts
Adds HTTP 422 status code common response codes.
Discussion - https://snyk.slack.com/archives/C040Q5G1Q3G/p1721036248223549
=> feat: add 422 status code

components/common.yaml
Updates sunset header documentation to be inline with implementation
=> fix: update sunset header

components/common.yaml
Follow up on the conversation in #ask-foundation https://snyk.slack.com/archives/C040Q5G1Q3G/p1731519198939549
Suggestions from the Content team https://docs.google.com/document/d/1tmd5GBCqbnGLyFKD0oyqAFhOnTAkbdUSQSG0quJIYQ4/edit?tab=t.0
=> fix: improve description for error status

end-end-tests/api-standards/resources/thing/2021-11-10/001-stability-change.yaml, end-end-tests/api-standards/test.bash, src/rulesets/rest/2022-05-25/__tests__/__snapshots__/lifecycle-rules.test.ts.snap, src/rulesets/rest/2022-05-25/__tests__/lifecycle-rules.test.ts, src/rulesets/rest/2022-05-25/lifecycle-rules.ts
- these upgrades are allowed after the pivot date
=> feat: allow inplace upgrades from beta to ga
